export const HIRAGANA = [
  { char: 'あ', romaji: 'a' }, { char: 'い', romaji: 'i' }, { char: 'う', romaji: 'u' }, { char: 'え', romaji: 'e' }, { char: 'お', romaji: 'o' },
  { char: 'か', romaji: 'ka' }, { char: 'き', romaji: 'ki' }, { char: 'く', romaji: 'ku' }, { char: 'け', romaji: 'ke' }, { char: 'こ', romaji: 'ko' },
  { char: 'さ', romaji: 'sa' }, { char: 'し', romaji: 'shi' }, { char: 'す', romaji: 'su' }, { char: 'se', romaji: 'se' }, { char: 'そ', romaji: 'so' },
  { char: 'た', romaji: 'ta' }, { char: 'ち', romaji: 'chi' }, { char: 'つ', romaji: 'tsu' }, { char: 'て', romaji: 'te' }, { char: 'と', romaji: 'to' },
  { char: 'な', romaji: 'na' }, { char: 'に', romaji: 'ni' }, { char: 'ぬ', romaji: 'nu' }, { char: 'ね', romaji: 'ne' }, { char: 'の', romaji: 'no' },
  { char: 'は', romaji: 'ha' }, { char: 'ひ', romaji: 'hi' }, { char: 'ふ', romaji: 'fu' }, { char: 'へ', romaji: 'he' }, { char: 'ほ', romaji: 'ho' },
  { char: 'ま', romaji: 'ma' }, { char: 'み', romaji: 'mi' }, { char: 'む', romaji: 'mu' }, { char: 'め', romaji: 'me' }, { char: 'も', romaji: 'mo' },
  { char: 'や', romaji: 'ya' }, { char: '', romaji: '' }, { char: 'ゆ', romaji: 'yu' }, { char: '', romaji: '' }, { char: 'よ', romaji: 'yo' },
  { char: 'ら', romaji: 'ra' }, { char: 'り', romaji: 'ri' }, { char: 'る', romaji: 'ru' }, { char: 'れ', romaji: 're' }, { char: 'ろ', romaji: 'ro' },
  { char: 'わ', romaji: 'wa' }, { char: '', romaji: '' }, { char: '', romaji: '' }, { char: '', romaji: '' }, { char: 'を', romaji: 'wo' },
  { char: 'ん', romaji: 'n' }
];

export const KATAKANA = [
  { char: 'ア', romaji: 'a' }, { char: 'イ', romaji: 'i' }, { char: 'ウ', romaji: 'u' }, { char: 'エ', romaji: 'e' }, { char: 'オ', romaji: 'o' },
  { char: 'カ', romaji: 'ka' }, { char: 'キ', romaji: 'ki' }, { char: 'ク', romaji: 'ku' }, { char: 'ケ', romaji: 'ke' }, { char: 'コ', romaji: 'ko' },
  { char: 'サ', romaji: 'sa' }, { char: 'シ', romaji: 'shi' }, { char: 'ス', romaji: 'su' }, { char: 'セ', romaji: 'se' }, { char: 'ソ', romaji: 'so' },
  { char: 'タ', romaji: 'ta' }, { char: 'チ', romaji: 'chi' }, { char: 'ツ', romaji: 'tsu' }, { char: 'テ', romaji: 'te' }, { char: 'ト', romaji: 'to' },
  { char: 'ナ', romaji: 'na' }, { char: 'ニ', romaji: 'ni' }, { char: 'ヌ', romaji: 'nu' }, { char: 'ネ', romaji: 'ne' }, { char: 'ノ', romaji: 'no' },
  { char: 'ハ', romaji: 'ha' }, { char: 'ヒ', romaji: 'hi' }, { char: 'フ', romaji: 'fu' }, { char: 'ヘ', romaji: 'he' }, { char: 'ホ', romaji: 'ho' },
  { char: 'マ', romaji: 'ma' }, { char: 'ミ', romaji: 'mi' }, { char: 'ム', romaji: 'mu' }, { char: 'メ', romaji: 'me' }, { char: 'モ', romaji: 'mo' },
  { char: 'ヤ', romaji: 'ya' }, { char: '', romaji: '' }, { char: 'ユ', romaji: 'yu' }, { char: '', romaji: '' }, { char: 'ヨ', romaji: 'yo' },
  { char: 'ラ', romaji: 'ra' }, { char: 'ri', romaji: 'ri' }, { char: 'ル', romaji: 'ru' }, { char: 'レ', romaji: 're' }, { char: 'ロ', romaji: 'ro' },
  { char: 'ワ', romaji: 'wa' }, { char: '', romaji: '' }, { char: '', romaji: '' }, { char: '', romaji: '' }, { char: 'ヲ', romaji: 'wo' },
  { char: 'ン', romaji: 'n' }
];

export const KANJI_N5 = [
  { char: '日', romaji: 'hi / nichi', meaning: 'Jour / Soleil' },
  { char: '本', romaji: 'hon', meaning: 'Livre / Origine' },
  { char: '人', romaji: 'hito / jin', meaning: 'Personne / Humain' },
  { char: '月', romaji: 'tsuki / getsu', meaning: 'Lune / Mois' },
  { char: '火', romaji: 'hi / ka', meaning: 'Feu' },
  { char: '水', romaji: 'mizu / sui', meaning: 'Eau' },
  { char: '木', romaji: 'ki / moku', meaning: 'Arbre / Bois' },
  { char: '金', romaji: 'kane / kin', meaning: 'Or / Argent' },
  { char: '土', romaji: 'tsuchi / to', meaning: 'Terre / Sol' },
  { char: '山', romaji: 'yama / san', meaning: 'Montagne' },
  { char: '川', romaji: 'kawa / sen', meaning: 'Rivière' },
  { char: '田', romaji: 'ta / den', meaning: 'Rizière' },
  { char: '口', romaji: 'kuchi / kō', meaning: 'Bouche / Entrée' },
  { char: '車', romaji: 'kuruma / sha', meaning: 'Voiture / Véhicule' },
  { char: '門', romaji: 'mon', meaning: 'Porte / Portail' },
  { char: '一', romaji: 'ichi', meaning: 'Un' },
  { char: '二', romaji: 'ni', meaning: 'Deux' },
  { char: '三', romaji: 'san', meaning: 'Trois' },
  { char: '四', romaji: 'yon / shi', meaning: 'Quatre' },
  { char: '五', romaji: 'go', meaning: 'Cinq' },
  { char: '六', romaji: 'roku', meaning: 'Six' },
  { char: '七', romaji: 'nana / shichi', meaning: 'Sept' },
  { char: '八', romaji: 'hachi', meaning: 'Huit' },
  { char: '九', romaji: 'kyū', meaning: 'Neuf' },
  { char: '十', romaji: 'jū', meaning: 'Dix' },
  { char: '百', romaji: 'hyaku', meaning: 'Cent' },
  { char: '千', romaji: 'sen', meaning: 'Mille' },
  { char: '万', romaji: 'man', meaning: 'Dix mille' },
  { char: '円', romaji: 'en', meaning: 'Yen / Rond' },
  { char: '上', romaji: 'ue / jō', meaning: 'Haut / Dessus' },
  { char: '下', romaji: 'shita / ka', meaning: 'Bas / Dessous' },
  { char: '左', romaji: 'hidari / sa', meaning: 'Gauche' },
  { char: '右', romaji: 'migi / u', meaning: 'Droite' },
  { char: '中', romaji: 'naka / chū', meaning: 'Milieu / Intérieur' },
  { char: '大', romaji: 'ō / dai', meaning: 'Grand' },
  { char: '小', romaji: 'chii / shō', meaning: 'Petit' }
];
